spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nationwide?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: asd1234


  jpa:
    open-in-view: false # View 영속성 제거
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

  #SMPT 이메일 인증
  mail:
    host: smtp.gmail.com          # 구글 SMTP 서버 주소
    port: 587                     # 구글 SMTP 포트 번호
    username: whwhwjddn123@gmail.com
    password: qbkejbzudkpjxfnw

    properties:
      mail:
        smtp:
          auth: true              # 사용자 인증 여부
          timeout: 5000           # 이메일 전송 타임아웃 시간
          starttls:
            enable: true          # TLS를 통해 안전한 통신 사용 여부

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  access-expiration-ms: 3600000
  refresh-expiration-ms: 604800000